# Generated by Django 2.2 on 2019-04-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editingproject',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editingproject',
            name='edit_file',
            field=models.FileField(blank=True, null=True, upload_to='textfile/'),
        ),
        migrations.AddField(
            model_name='editingproject',
            name='edit_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editingproject',
            name='final_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editingproject',
            name='orig_file',
            field=models.FileField(blank=True, null=True, upload_to='textfile/'),
        ),
    ]
