# Generated by Django 2.2 on 2019-04-29 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0002_auto_20190429_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='editingproject',
            name='orig_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='editingproject',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
