# Generated by Django 2.2 on 2019-05-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0003_auto_20190429_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='editingproject',
            name='proj_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
