# Generated by Django 2.2 on 2019-05-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0004_editingproject_proj_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editingproject',
            old_name='proj_name',
            new_name='project',
        ),
    ]
