# Generated by Django 2.2 on 2019-05-03 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0006_auto_20190503_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editingproject',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='brevisapp.ClientProfile'),
        ),
        migrations.AlterField(
            model_name='editingproject',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='brevisapp.EditorProfile'),
        ),
        migrations.AlterField(
            model_name='editorprofile',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
