# Generated by Django 2.2 on 2019-05-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0007_auto_20190503_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorprofile',
            old_name='client',
            new_name='user',
        ),
    ]
