# Generated by Django 2.2 on 2019-05-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0008_auto_20190503_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='editingproject',
            name='turnaround',
            field=models.BooleanField(default='False'),
        ),
    ]
