# Generated by Django 2.2 on 2019-05-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0009_editingproject_turnaround'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editingproject',
            old_name='project',
            new_name='name',
        ),
    ]
