# Generated by Django 2.2 on 2019-05-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0010_auto_20190507_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='editingproject',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
