# Generated by Django 2.2 on 2019-05-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0011_editingproject_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editingproject',
            old_name='name',
            new_name='proj_name',
        ),
    ]
