# Generated by Django 2.2 on 2019-05-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0012_auto_20190513_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editingproject',
            old_name='proj_name',
            new_name='name',
        ),
    ]
