# Generated by Django 2.2 on 2019-05-14 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevisapp', '0015_auto_20190513_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('reply', models.TextField(default='')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevisapp.EditingProject')),
            ],
        ),
    ]
